module.exports = {
  vendors: [
    // 'prop-types',
    // 'react',
    // 'react-dom',
    // 'react-router-dom',
    // 'connected-react-router',
    // 'react-redux',
    // 'redux',
    // 'redux-saga',

    'amdefine',
    'axios',
    'classnames',
    'filesize',
    'history',
    'invariant',
    'jsrsasign',
    'lodash',
    'moment',
    'oidc-client',
    'prop-types',
    'qs',
    'react',
    'react-day-picker',
    'react-dom',
    'react-redux',
    'react-router-dom',
    'connected-react-router',
    'redux',
    'redux-actions',
    'redux-oidc',
    'redux-saga',
    'reselect',
  ]
};
